---
- name: Gather facts
  hosts: all
  tags: always
  gather_facts: false
  tasks:
    - name: Gather minimal facts
      ansible.builtin.setup:

- name: Example file
  hosts: all
  gather_facts: false
  collections:
    - develtime.utils
  roles:
    - example
