---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    elasticsearch:
      hosts:
        el_instance_1:
          ansible_host: 192.168.8.177
    kibana:
      hosts:
        kbn_instance_1:
          ansible_host: 192.168.9.16
    filebeat:
      hosts:
        fb_instance_1:
          ansible_host: 192.168.8.208
